### ISSUE TITLE
Do we need to clear volumes. What if I need to add this protocol mapper in an existing project?

### ISSUE THREAD

**Issue by DennisMuchiri** [mschwartau/keycloak-custom-protocol-mapper-example#5]

**Comment by DennisMuchiri** [comment]
@mschwartau Please help.

**Comment by mschwartau** [comment]
Without knowing your project setup it is hard to help you. This project is only an example how it could be done. 

Nevertheless in your case I would check out the keycloak provider documentation because the custom protocol mapper ist just a provider. See https://www.keycloak.org/server/configuration-provider
